### ISSUE TITLE
Error using with dogstatsd-ruby

### ISSUE THREAD

**Issue by stereobooster** [basecamp/trashed#13]
I had this naive idea that DataDog dogstatsd-ruby will be compatible with this gem, but I'm suppose not. Looking into this myself, but in case somebody else will find answer before me

```
app error: undefined method `[]' for 0.1:float (nomethoderror)
/dogstatsd-ruby-3.0.0/lib/datadog/statsd.rb:390:in `send_stats'
/dogstatsd-ruby-3.0.0/lib/datadog/statsd.rb:198:in `timing'
/trashed-3.2.6/lib/trashed/reporter.rb:91:in `block (2 levels) in send_to_statsd'
/trashed-3.2.6/lib/trashed/reporter.rb:90:in `each'
/trashed-3.2.6/lib/trashed/reporter.rb:90:in `block in send_to_statsd'
/trashed-3.2.6/lib/trashed/reporter.rb:83:in `each'
/trashed-3.2.6/lib/trashed/reporter.rb:83:in `send_to_statsd'
/trashed-3.2.6/lib/trashed/reporter.rb:77:in `block in report_statsd'
/dogstatsd-ruby-3.0.0/lib/datadog/statsd.rb:307:in `batch'
/trashed-3.2.6/lib/trashed/reporter.rb:76:in `report_statsd'
/trashed-3.2.6/lib/trashed/reporter.rb:22:in `report'
/trashed-3.2.6/lib/trashed/rack.rb:18:in `block in call'
/trashed-3.2.6/lib/trashed/rack.rb:18:in `tap'
/trashed-3.2.6/lib/trashed/rack.rb:18:in `call'
/rack-contrib-1.5.0/lib/rack/contrib/runtime.rb:18:in `call'
/rack-contrib-1.5.0/lib/rack/contrib/sendfile.rb:99:in `call'
/railties-4.2.8/lib/rails/engine.rb:518:in `call'
/railties-4.2.8/lib/rails/application.rb:165:in `call'
/railties-4.2.8/lib/rails/railtie.rb:194:in `public_send'
/railties-4.2.8/lib/rails/railtie.rb:194:in `method_missing'
/unicorn-5.2.0/lib/unicorn/http_server.rb:562:in `process_client'
/unicorn-5.2.0/lib/unicorn/http_server.rb:658:in `worker_loop'
/unicorn-5.2.0/lib/unicorn/http_server.rb:508:in `spawn_missing_workers'
/unicorn-5.2.0/lib/unicorn/http_server.rb:132:in `start'
/unicorn-5.2.0/bin/unicorn:126:in `<top (required)>'
/bin/unicorn:22:in `load'
/bin/unicorn:22:in `<main>'
```

**Comment by stereobooster** [comment]
This is what I needed to change in `reporter.rb`:

```diff
Array(dimensions || :All).each do |dimension|
-   statsd.send method, :"#{namespace}.#{dimension}.#{metric}", value, sample_rate
+   statsd.send method, :"#{namespace}.#{dimension}.#{metric}", value, { sample_rate: sample_rate }
end
```

The question is why. Is it should be addressed in this gem or in datadog gem?

**Comment by jeremy** [comment]
dogstatsd-ruby [changed](https://github.com/DataDog/dogstatsd-ruby/commit/b1180303625c5dfbb45a44f62f21c3af65afa54c#diff-179756856cd1fe6003145224a9f4f979) the StatsD client method signature, so it's not drop-in compatible.

**Comment by stereobooster** [comment]
In case anybody else interested. Here is a hack to overcome it

```ruby
module Application
  class Statsd < ::Datadog::Statsd
    alias_method :datadog_count, :count
    def count(stat, count, sample_rate = 1)
      datadog_count(stat, count, sample_rate: sample_rate)
    end

    alias_method :datadog_gauge, :gauge
    def gauge(stat, value, sample_rate = 1)
      datadog_gauge(stat, value, sample_rate: sample_rate)
    end

    alias_method :datadog_timing, :timing
    def timing(stat, ms, sample_rate = 1)
      datadog_timing(stat, ms, sample_rate: sample_rate)
    end

    alias_method :datadog_time, :time
    def time(stat, sample_rate = 1)
      datadog_time(stat, sample_rate: sample_rate)
    end
  end
end
```
