### ISSUE TITLE
ConcurrencyError: Detected invalid array contents due to unsynchronized modifications with concurrent users

### ISSUE THREAD

**Issue by swistaczek** [basecamp/trashed#4]
``` ruby
Stacktrace (most recent call first):

  org/jruby/RubyArray.java:1613:in `each'
  org/jruby/RubyEnumerable.java:977:in `each_with_index'
  trashed/instruments/ruby_gc_profiler.rb:12:in `measure'
    timings[:"#{captured}.time"] ||= 1000 * GC::Profiler.total_time
  trashed/instruments/ruby_gc_profiler.rb:7:in `start'
    measure state, timings, gauges, :OOBGC
  trashed/meter.rb:31:in `instrument!'
    @timers.each { |i| i.start state, timings, gauges }
```

**Comment by madhurkgp** [comment]
I'm facing the same issue, did you got any solution or workaround for this problem ?

any lead would help.
